# Generated by Django 5.2.5 on 2025-08-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIpj', '0003_activitytype_coords_image_level_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': 'Вид активности', 'verbose_name_plural': 'Виды активности'},
        ),
    ]
