# Generated by Django 5.2.5 on 2025-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIpj', '0004_alter_activitytype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
