# Generated by Django 5.2.5 on 2025-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIpj', '0005_alter_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Телефон'),
        ),
    ]
